### ISSUE TITLE
Some examples

### ISSUE THREAD

**Issue by autodidaddict** [YellowInnovation/nitox#10]
There are virtually no examples of using this library. The test suite is extremely difficult to read for people who are new to (or dislike) tokio syntax. For example, how does one create something that subscribes to a topic and replies with a value, and the app does this indefinitely like a real service might? 

I'm trying to get something like this working (subscribe to "X", reply with "Y" ), but copying the test code the app (w/out the `runtime.shutdown`), the app terminates immediately. Just a simple "listener" demo and a simple "sender" demo would be _extremely_ helpful.

**Comment by o0Ignition0o** [comment]
This is very true, I'll try to work on a couple of examples. @OtaK I wonder if adding it to the main page would be sufficient, or if having a wiki would be more convenient ?

**Comment by o0Ignition0o** [comment]
If you would like to see how it works in the meantime, https://github.com/YellowInnovation/actix-nats/blob/master/src/lib.rs is an actix nats actor which uses nitox under the hood, nitox's client.request and subscribe functions probably being the most interesting ones :D

**Comment by o0Ignition0o** [comment]
I'll probably blog about how to handle messages, since it requires a lot of context on how to handle futures / streams / sink etc... 

I struggled a lot with it at first so trying to explain it it might be a great exercise for me. 
@autodidaddict would you mind proofreading an article on the topic if I get enough time to write one ? :)

**Comment by Southclaws** [comment]
I'd be interested in this too! I've been wrestling with getting something working for a while - it doesn't help that I'm a Rust newcomer but some examples/blogs would be great!

**Comment by o0Ignition0o** [comment]
We have a deal then :) , I'll probably publish something on the basics of futures / streams, and how to handle receiving messages. 
Oh and by the way the [five parts blog post on futures and streams](https://dev.to/mindflavor/rust-futures-an-uneducated-short-and-hopefully-not-boring-tutorial---part-1-3k3) I refer to on the pull request helped me a lot ! :)

**Comment by OtaK** [comment]
I agree that we need more docs and examples to get stuff running and understand stuff.

I'd like to note that nitox is used in production and works perfectly well, so the fault is really on my lack of attention to docs and stuff.

I've been looking forward to release the v0.2.0 with NATS Streaming Server support and a general overhaul of some internals: 
- Documentation/examples effort
- Using `hashbrown` to get some additional free speedups and memory efficiency improvements
- Parser improvements, I still need to work on it to get it with the safety it needs (I added some unwraps to my current improvements so it's not what we want).
- NATS Streaming Server / STAN support

Unfortunately, we've been caught up with some very urgent tasks lately so we'll try to catch up on that soon :)

**Comment by autodidaddict** [comment]
If you take a look at this code:
```
let fut_responder = NatsClient::from_options(options.clone())
        .and_then(|client| client.connect())
        .and_then(|client| {
            let sub_command = 
            SubCommand::builder().subject("foo.bar").build().unwrap();
            client
                .subscribe(sub_command)
                .map_err(|_| NatsError::InnerBrokenChain)                
                .and_then(move |sub_stream| spawn_responder(client, sub_stream))
        }).map_err(|_|());
    
    tokio::run(fut_responder);
```
This immediately exits the application. What I really want is the subscriber to stay active forever. This actually worked briefly but now for some reason it exits immediately. Nothing in the actix example helps me get to this ultra basic level, the "hello world" of pubsub - subscribe to a topic, always reply with "hello", and never terminate the app.

**Comment by autodidaddict** [comment]
I just recompiled the same code and this time it doesn't immediately terminate. 😕

**Comment by o0Ignition0o** [comment]
https://github.com/o0Ignition0o/nitox-count-to-a-million/blob/master/src/main.rs is pretty much the project I'll base the blogpost from.

I need to add a bit of (rx,tx) and a bit of streaming for it to be interesting, but it looks a lot like the code snippet you have written :)

**Comment by o0Ignition0o** [comment]
https://github.com/o0Ignition0o/nitox-count-to-a-million/blob/master/src/main.rs There is now a message handler, which prints the message (in debug mode) @Southclaws Please have a look at it while I'm adding features, and let me know if you have any questions :)

**Comment by autodidaddict** [comment]
I'm looking at this example and I can't figure out how to subscribe to two topics using this structure. In each of these blocks:
```
client
        .subscribe(SubCommand::builder().subject("Race").build().unwrap())
        .and_then(move |message_stream| handle_message_stream(message_stream))
        .and_then(|_| ok(client))
```

I get an error indicating a second move of client. I tried converting things to a reference to client and that made things horribly worse.

**Comment by autodidaddict** [comment]
One thought I had was to use a channel - and within the subscribe handler spawn, emit the reply on the channel, and then have another  spawned thing that would take stuff off a channel and just publish on nats reply topic... but I can't get that working either, because I can't get the channels to do a `for_each(...).into_future()` ... 

The tokio syntax makes all of this soooo much harder than it should be. The equivalent in Go is brain-dead simple.

**Comment by Southclaws** [comment]
I'm also coming from Go and having a tough time getting to know how Tokio does things!

That being said, I've got a simple reader working now thanks to this issue thread! (Thanks everyone)

The one thing I'm having trouble with is setting subscription options because I want to read from the beginning of the stream then stop, rather than listen continuously (for a re-index operation).

**Comment by autodidaddict** [comment]
I did manage to figure out how to get two different subscribers to both publish on the reply topic without having the double-move compilation failure. I am putting the `NatsClient` in an `Arc` and cloning the `Arc` when sending it to the stream handler function.

**Comment by o0Ignition0o** [comment]
I think the NatsClient is Send+Sync, so I'm not really sure putting it into an Arc would be efficient / useful.

I've just submitted a pull request with a marco/polo request reply example, is it of any use for you ?

**Comment by o0Ignition0o** [comment]
@Southclaws I'm sorry I didn't notice your post, I was focused on the marco-polo example ^^'

I don't think NATS has been designed to replay a full stream history. You can however subscribe to a topic and then immediately unsubscribe with a number of messages you want to receive before shutting the subscriber down as shown [here](https://docs.rs/nitox/0.1.9/nitox/commands/struct.UnsubCommand.html#structfield.max_msgs). 

This is actually the way we designed the [Request command](https://github.com/YellowInnovation/nitox/blob/master/src/client.rs#L400) so feel free to use it as an example before I write one :)

The implementation follows the specification of the NATS Client Protocol, which you can find [here](https://nats.io/documentation/internals/nats-protocol/#UNSUB)

Please let me know if it helps :)

**Comment by OtaK** [comment]
#12 Has been merged as the first example, please take a look, we'll try to add more with the time we have :)

**Comment by Southclaws** [comment]
Reading the entire stream is something we're doing in production to re-project state, but we're using the Go client (most of the stuff is in Go anyway - I'm just experimenting with Rust). I also forgot to mention I was referring to NATS Streaming, not regular NATS (we don't even use NATS without the Streaming extension so I'm so used to just calling it NATS!)

I think I just need to set the `startPosition` on the subscription request, but I'm not entirely sure how to build a subscription options object with that field set to `First`. I know the streaming branch is currently in development so I might just wait until it's merged and documented.

**Comment by o0Ignition0o** [comment]
Oh I see, nats Streaming support is part of our next milestone(s) so maybe I can let you know when it's up and running =)

**Comment by OtaK** [comment]
Ah yes indeed, NATS Streaming Server / STAN will be available as part of 0.2 as mentioned before 😅

**Comment by OtaK** [comment]
Should we close this since it's stale and we have some examples going on already?

Thoughts @o0Ignition0o?

**Comment by o0Ignition0o** [comment]
Yeah let's close it (Sorry I have totally forgotten about this issue :o)
