### ISSUE TITLE
How to Disconnect Client

### ISSUE THREAD

**Issue by nevi-me** [YellowInnovation/nitox#6]
I'm using nitox inside a loop, where in each run of the loop, I create a new connection.

```rust
loop {
  // create connection
  // do work
}
```

I tried creating my connection outside of the loop, but el compiler was complaining that `NatsClient` does not implement `Copy`.

Is there currently a way of disconnecting a client? My clients aren't getting disconnected after my loop completes, as a result I have a growing list of open connections showing on `nats:8222/connz`.

**Comment by OtaK** [comment]
Disconnecting is currently not implemented because you can just `drop` the client.

Also, I don't really see why you would spawn futures in a synchronous loop?

**Comment by nevi-me** [comment]
@OtaK coincidentally I'm the guy who was asking about turning a database cursor into a stream, on gitter last night.

Re the loop, I missed out some detail.

I use the loop to 'run forever', but I actually do the below:

```rust
loop {
  let task = tokio::Interval::new(...).map(move |interval| {
    let nats_cn = NatsClient::from_options(...).wait().unwrap();

    let cursor_stream = get_stream_fn();
    cursor_stream.for_each(|doc| {
      nats_cn.publish(doc);
    })
  })
}
```

Unless my `Interval` stream fails, the loop has no impact (I think). So the problem's that my connection doesn't get dropped after I consume my `cursor_stream`.

**Comment by OtaK** [comment]
Oh cool! Nice to see you around here.

Well I think you might have a misunderstanding of futures/streams in general; using `wait` is generally very bad practice as it nullifies the gains of async I/O, i.e it blocks the threads.

The following code would be more idiomatic:

```rust
NatsClient::from_options(...)
    .and_then(|client| client.connect())
    .and_then(|client| {
        get_stream_fn.for_each(|doc| {
            let pub_cmd = PubCommand::builder()
                .subject("my-queue")
                .payload(doc.into())
                .build()
                .unwrap();
                
            client.publish(pub_cmd)
        }).into_future()
    })
    .and_then(|_| {
        println!("Done");
    })
```

**Comment by nevi-me** [comment]
Thanks for helping @OtaK, I'm honestly not winning, the above hasn't helped me out, not an issue with nitox, but problem between me and Rust.

I'll reopen this issue if after my hurdle, the connection still doesn't get dropped.

**Comment by nevi-me** [comment]
Hi @OtaK this is still a problem, my connections aren't getting dropped/closed. The code that you suggested doesn't work because of a lifetime issue with the client. I can't clone the client, and I tried wrapping it in an `Arc` but that didn't work.

I end up with a `too many files open` error after a 1000 connections are open

**Comment by OtaK** [comment]
You shouldn't open more than one connection at a time; There's no use case that would warrant 1000 clients open in a given process. Please look at the examples in the `test/` folder

**Comment by o0Ignition0o** [comment]
Hey @nevi-me :)

Mind sharing a gist ? I'll try to have a look at it and figure out what you mean :)

**Comment by o0Ignition0o** [comment]
Hey @nevi-me :)

Mind sharing a gist ? I'll try to have a look at it and figure out what you mean :)

**Comment by nevi-me** [comment]
Hi @o0Ignition0o , here's a gist: https://gist.github.com/nevi-me/f1920e0b51c260d2ac52786a0cbccc2a. Please bear in mind that a part of my problem might be because I don't understand some Rust concepts well, I'm finding it a difficult (but rewarding) language.

**Comment by o0Ignition0o** [comment]
Hi :) thanks a lot for the readme explanation, which is really helpful :)

From what I understand, you're tring to listen to a db_client and send the events to nats, preferably using a stream interface. This is a great idea, even though there is probably no need to 'create a new client' on each loop iteration. Plus as everything here is being async, this would probably end up pinning a huge number of clients :) 

What we may want to do instead is : 

- create a nats client
- handle reconnection if the client fails
- Every 7 seconds, grab the new items and send them using the nats client :)

A neat way to learn about streams would be to : 
- create a stream "creator" ([which is called a Sink](https://docs.rs/futures/0.1/futures/sink/trait.Sink.html ) - the link is down right now but it will be back up soon :) )
- Every 7 seconds, grab the new items and write them to the sink.
- Iterate over the created stream to publish each new item.

I feel like this article [on creating a stream over a pagination](http://xion.io/post/code/rust-unfold-pagination.html) and this one [on streaming two protocols](https://medium.com/@KevinHoffman/streaming-grpc-with-rust-d978fece5ef6) would come in handy :)

If you want to dig a bit deeper, note there's also a handy way to handle some database notifications, here's [a Postgresql example ](https://tapoueh.org/blog/2018/07/postgresql-listen/notify/).
I hope there also is such an interface for your favorite db client :)

**Comment by thedodd** [comment]
Hey guys, I know this issue is closed, but even if you are only ever opening one nats connection, this still blocks the possibility of graceful shutdown (which can be an issue, and is for me).

Check out #22. I've written up a test case which shows the problem in more detail, and also a proposal on how we can fix this. Shouldn't be too difficult.
